In [18]:
import sqlite3
import pandas as pd


def open_db():
   conn = sqlite3.connect('exercise2.db')
   c = conn.cursor()
   return (c,conn)

def close_db(c):
   c.commit()
   c.close()

def build_assessments_table():
   c, conn = open_db()

   c.execute('''CREATE TABLE IF NOT EXISTS assessments(
                code_module TEXT,
                code_presentation TEXT,
                id_assessment INTEGER,
                assessment_type TEXT,
                date INT,
                weight INT
            )''')
   close_db(conn)

def build_courses_table():
    c,conn = open_db()

    c.execute('''CREATE TABLE IF NOT EXISTS courses(
                code_module TEXT,
                code_presentation TEXT,
                module_presentation_length INTEGER
                )''')
    conn.commit()
    conn.close()

def build_student_assessment_table():
    c,conn = open_db()

    c.execute('''CREATE TABLE IF NOT EXISTS student_assessments(
                    id_assessment INTEGER,
                    id_student INTEGER,
                    date_submitted INTEGER,
                    is_banked INTEGER,
                    score INTEGER
                )''')
    conn.commit()
    conn.close()


def build_student_info_table():
    c,conn = open_db()
    c.execute('''CREATE TABLE IF NOT EXISTS student_info(
                code_module TEXT,
                code_presentation TEXT,
                id_student INTEGER,
                gender TEXT,
                region TEXT,
                highest_education TEXT,
                imd_band TEXT, 
                age_band TEXT, 
                num_of_prev_attempts INTEGER,
                studied_credits INTEGER,
                disability TEXT,
                final_result TEXT
            )''')
    conn.commit()
    conn.close()

def build_student_reg_table():
    c,conn = open_db()
    c.execute('''CREATE TABLE IF NOT EXISTS student_registration(
                code_module TEXT,
                code_presentation TEXT,
                id_student INTEGER,
                date_registration INTEGER,
                date_unregistration INTEGER
        )''')
    conn.commit()
    conn.close()

def build_vle_table():
    c,conn = open_db()
    c.execute('''CREATE TABLE IF NOT EXISTS vle(
                id_site INTEGER,
                code_module TEXT,
                code_presentation TEXT,
                activity_type TEXT,
                week_from INTEGER,
                week_to INTEGER
            )''')
    conn.commit()
    conn.close()

# build_assessments_table()
# build_courses_table()
# build_student_assessment_table()
# build_student_info_table()
# build_student_reg_table()
# build_vle_table()

## SET TABLE DATA USING ITERATION OR PANDAS
### CLEAR TABLE DATA FUNCTION

In [48]:
import os
import csv
import pandas as pd

def execute_command(command):
   conn = sqlite3.connect('exercise2.db')
   c = conn.cursor()
   c.execute(command)
   conn.commit()
   conn.close()

# SET ASSESSMENT DATA USING CSV READER AND ITERATING OVER ROWS
def set_assessment_data():
   with open('data/assessments.csv', 'rt') as fin:
      reader = csv.reader(fin)
      print(reader)
      #skip header row
      next(reader)

      to_db = [(row[0], row[1], row[2], row[3], row[4], row[5]) for row in reader]
    #   headers = "code_module","code_presentation","id_assessment","assessment_type","date","weight"
      c,conn = open_db()

      command = 'INSERT INTO assessments VALUES (?,?,?,?,?,?);'
      c.executemany(command, to_db)

      close_db(conn)
# SET COURSES DATA USING CSV READER AND ITERATING OVER ROWS
def set_courses_table():
    with open('data/courses.csv', 'rt') as fin:
        reader = csv.reader(fin)
        next(reader)
        to_db = [(row[0], row[1], row[2]) for row in reader]
        
        c,conn = open_db()
        command = 'INSERT INTO courses VALUES (?,?,?);'
        c.executemany(command, to_db)
        close_db(conn)
# SET COURSES DATA USING PANDAS AND .to_sql
def set_courses_with_pd():
    df = pd.read_csv('data/courses.csv')
    c,conn = open_db()
    df.to_sql('courses', conn, if_exists='replace', index=False)
    close_db(conn)

# DELETE ANY TABLE DATA USING TABLE NAME
def clear_table_data(table_name):
    command = 'DELETE FROM ' + table_name
    execute_command(command)

# SET ANY TABLE DATA FROM CSV FILE USING PANDAS DATAFRAME
def set_table_data(table_name, file_path):
    df = pd.read_csv(file_path)
    c,conn = open_db()
    df.to_sql(table_name, conn, if_exists='replace')
    close_db(conn)

# set_table_data('student_assessments','data/studentAssessment.csv')
# set_table_data('vle','data/vle.csv')

## GET RESULTS FROM A TABLE

In [59]:
def print_results(results):
   results = results.fetchall()
   print(results)
   for res in results:
      print(res)

def read_from_table(name):
    command = 'SELECT * FROM ' + name
    print(command)
    c,conn = open_db()
    results = c.execute(command).fetchall()
    print(len(results))
    close_db(conn)
    return results

results = read_from_table('courses')

SELECT * FROM courses
22

## GET COUNT SUM AND AVE VALUES FOR COLUMNS

In [76]:
def get_count(table_name):
    c,conn = open_db()
    command = 'SELECT COUNT(*) FROM ' + table_name
    result = c.execute(command).fetchone()
    close_db(conn)
    return result

get_count('assessments')

def get_sum(table_name, col_name):
    c,conn = open_db()
    command = 'SELECT SUM(' + col_name + ') FROM ' + table_name
    result = c.execute(command).fetchone()
    close_db(conn)
    return result

get_sum('courses', 'module_presentation_length')

def get_avg(table_name, col_name):
    c,conn = open_db()
    command = 'SELECT AVG(' + col_name + ') FROM ' + table_name
    result = c.execute(command).fetchone()
    close_db(conn)
    return result

get_avg('courses', 'module_presentation_length')

(255.54545454545453,)